<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE garage[
    <!-- Déclaration des entités internes -->
    <!ENTITY dacia "Dacia">
    <!ENTITY renault "Renault">
    <!ENTITY citroen "Citroën">
    <!ENTITY % listeMarque "(pioneer|alpine)  #REQUIRED">

    <!-- Déclaration des éléments -->
    <!ELEMENT garage (voiture*)>
        <!ELEMENT voiture (marque, autoradio)*>
            <!ELEMENT marque (#PCDATA)>
            <!ELEMENT autoradio EMPTY>
                <!ATTLIST autoradio %listeMarque;>
]>

<garage>
    <voiture>
        <marque>&dacia</marque>
        <autoradio modele="pionner" />
    </voiture>
    <voiture>
        <marque>&renault</marque>
    </voiture>
    <voiture>
        <marque>&citroen</marque>
    </voiture>
    <voiture>
        <marque>Hyundai</marque>
    </voiture>
</garage>