<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- déclaration des DTD -->
<!DOCTYPE rolodex [
    <!ELEMENT rolodex (contact*)>
        <!ELEMENT contact (nom, prenom*, adresses, emails)>
        <!ATTLIST contact personne (physique | morale) "physique">
        <!ATTLIST contact numero ID #REQUIRED>
            <!ELEMENT nom (#PCDATA)>
            <!ELEMENT prenom (#PCDATA | surnom)*>
                <!ELEMENT surnom (#PCDATA)>
            <!ELEMENT adresses (adresse*)>
                <!ELEMENT adresse (numero, voie, codePostal, ville, pays)>
                <!ATTLIST adresse type (facturation | livraison) #REQUIRED>
                <!-- si une donnée est indiquée par défaut, l'attribut n'a pas besoin d'être obligatoire -->
                <!-- <!ATTLIST adresse type (facturation | livraison) "facturation"> -->
                <!ATTLIST adresse userAdresse IDREF #REQUIRED>
                    <!ELEMENT numero (#PCDATA)>
                    <!ELEMENT voie (#PCDATA)>
                    <!ATTLIST voie type (rue | avenue | boulevard | impasse | place | faubourg | route | chemin | voie) #REQUIRED>
                    <!ELEMENT codePostal (#PCDATA)>
                    <!ELEMENT ville (#PCDATA)>
                    <!ELEMENT pays (#PCDATA)>
            <!ELEMENT emails (email+)>
                <!ELEMENT email (#PCDATA)>
                <!ATTLIST email type (personnel | professionnel) "personnel">

]>
<rolodex>
    <!-- Jean Durand, ACME Inc. CEO -->
    <contact personne="physique" numero="n1">
        <nom>Durand</nom>
        <prenom>
            Jean
            <surnom>Dudu</surnom>
        </prenom>
        <prenom>Marc</prenom>
        <adresses>
            <adresse type="facturation" userAdresse="n1">
                <numero>7</numero>
                <voie type="impasse">Impasse du chemin</voie>
                <codePostal>75015</codePostal>
                <ville>Paris</ville>
                <pays>FRANCE</pays>
            </adresse>
            <adresse type="livraison" userAdresse="n1">
                <numero>7</numero>
                <voie type="impasse">Impasse du chemin</voie>
                <codePostal>75015</codePostal>
                <ville>Paris</ville>
                <pays>FRANCE</pays>
            </adresse>
        </adresses>
        <emails>
            <email type="personnel">jean_durand@yahoo.fr</email>
            <email type="professionnel">jdurand@acme.com</email>
        </emails>
    </contact>
    <!-- ACME Inc. -->
    <contact personne="morale" numero="n2">
        <nom>ACME Inc.</nom>
        <adresses>
            <adresse type="facturation" userAdresse="n1">
                <numero>7</numero>
                <voie type="impasse">Impasse du chemin</voie>
                <codePostal>75015</codePostal>
                <ville>Paris</ville>
                <pays>FRANCE</pays>
            </adresse>
            <adresse type="livraison" userAdresse="n1">
                <numero>7</numero>
                <voie type="impasse">Impasse du chemin</voie>
                <codePostal>75015</codePostal>
                <ville>Paris</ville>
                <pays>FRANCE</pays>
            </adresse>
            <adresse type="livraison" userAdresse="n1">
                <numero>14</numero>
                <voie type="place">Place des États-unis</voie>
                <codePostal>75016</codePostal>
                <ville>Paris</ville>
                <pays>FRANCE</pays>
            </adresse>
        </adresses>
        <emails>
            <email type="professionnel">contact@acme.com</email>
            <email type="professionnel">sav@acme.com</email>
            <email type="professionnel">evenenement@acme.com</email>
        </emails>
    </contact>
</rolodex>